### ISSUE TITLE
Wrong AVCaptureVideoOrientation when not landscapeRight or portrait

### ISSUE THREAD

**Issue by MalekIhdene** [OutSystems/OSBarcodeLib-iOS#18]
Hello,
I have this issue with the library whereas whenever I specify a mode and my IPAD is not in the landscapeRight mode (landscapeLeft) or portrait (portraitUpsideDown) then the camera will be upside down on the IPAD.
<img width="901" alt="Screenshot 2024-08-05 at 9 43 58 AM" src="https://github.com/user-attachments/assets/bdfa5ebc-fe26-4023-a237-a4d958450df2">
i.e. the video capture will be inverted in a way that is not desired. I was wondering if this is a limitation.

**Comment by OS-ricardomoreirasilva** [comment]
Hey @MalekIhdene,

Can you provide more information about the issue you're facing? Stuff like the device you're using, the iOS version, how you're calling the method to scan, etc would be helpful to troubleshoot the issue.

Thanks.

**Comment by MalekIhdene** [comment]
IpadOS Version: 17.5.1
Model Name: iPad (7th generation)
Model Number: MW742VC/A

I'm actually using a Capacitor plugin that uses this library as follows:
```
// swiftlint:disable line_length
import Foundation
import Capacitor
import OSBarcodeLib

@objc(CapacitorBarcodeScannerPlugin)
public class CapacitorBarcodeScannerPlugin: CAPPlugin {
    var manager: OSBARCManagerProtocol?

    override public func load() {
        guard let viewController = self.bridge?.viewController else {
            CAPLog.print("Error (Barcode Plugin Load): Capacitor bridge or viewController is not initialized.")
            return
        }

        self.manager = OSBARCManagerFactory.createManager(with: viewController)
    }

    @objc func scanBarcode(_ call: CAPPluginCall) {
        if self.manager == nil {
            self.load()
        }

        guard let manager = self.manager else {
            call.reject("Capacitor bridge or viewController is not initialized.")
            return
        }

        guard let argumentsData = try? JSONSerialization.data(withJSONObject: call.jsObjectRepresentation),
              let scanArguments = try? JSONDecoder().decode(OSBarcodeScanArgumentsModel.self, from: argumentsData) else {
            call.reject("Error decoding scan arguments")
            return
        }

        Task {
            do {
                let scannedBarcode = try await manager.scanBarcode(with: scanArguments.scanInstructions, scanArguments.scanButtonText, scanArguments.cameraDirection, and: scanArguments.scanOrientation)
                call.resolve(["ScanResult": scannedBarcode])
            } catch OSBARCManagerError.cameraAccessDenied {
                call.reject("Camera access denied")
            } catch OSBARCManagerError.scanningCancelled {
                call.reject("Scanning cancelled")
            } catch {
                call.reject("An unexpected error occurred: \(error.localizedDescription)")
            }
        }
    }
}
```
https://github.com/ionic-team/capacitor-barcode-scanner/blob/main/plugin/ios/Plugin/CapacitorBarcodeScannerPlugin.swift
I'm passing `FRONT = 2`  as camera direction and `LANDSCAPE = 2` as scan orientation.
The values are mapped as such by the JSON decoder so its all fine and dandy:
![image](https://github.com/user-attachments/assets/052e5faa-395d-4c2f-9325-8cfa502dabdf)
![image](https://github.com/user-attachments/assets/0f12efc8-5ac1-49e3-ba14-846501069847)
I'm essentially calling:
`await manager.scanBarcode(with: "Scan your badge QR code", "", .front, and: .landscape)`

What exactly happens is that whenever I'm not in the primary portrait or landscape orientations. The UI of the QR code scanner is fine but the camera feed is inverted.

I can then flip the iPad twice to get back to the secondary orientation and now the camera feed is in the right direction. It is only initially when I first call the function that the orientation is not the right one.

**Comment by OS-ricardomoreirasilva** [comment]
Thanks for sharing the info. One last thing: What are the iPad Orientations you're enabling for your app?

**Comment by MalekIhdene** [comment]
Straight out of the `Info.plist` file
```
<key>UISupportedInterfaceOrientations</key>
<array>
<string>UIInterfaceOrientationLandscapeLeft</string>
<string>UIInterfaceOrientationLandscapeRight</string>
<string>UIInterfaceOrientationPortrait</string>
</array>
<key>UISupportedInterfaceOrientations~ipad</key>
<array>
<string>UIInterfaceOrientationLandscapeLeft</string>
<string>UIInterfaceOrientationLandscapeRight</string>
<string>UIInterfaceOrientationPortrait</string>
</array>
```

**Comment by OS-ricardomoreirasilva** [comment]
Ok, I was able to reproduce your issue, so the next version of the library should have it fixed. 👍

**Comment by MalekIhdene** [comment]
@OS-ricardomoreirasilva Do you have a rough timeline of when the next version will be released? Are we talking weeks or months? Thank you for your hard work!

**Comment by OS-ricardomoreirasilva** [comment]
> @OS-ricardomoreirasilva Do you have a rough timeline of when the next version will be released? Are we talking weeks or months? Thank you for your hard work!

We've just released a new version of the lib on CocoaPods. It should already be available for you to use on your project.
